### ISSUE TITLE
Extract Products/SiteAccess?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/ZServer#4]
The `VirtualHostMonster` seems to be perfectly usable with a WSGI setup. (We use it in Zope 2.13 with the WSGI publisher.)

I think it should either be moved back to the `Zope` package or into a separate package `Products.SiteAccess`.

Or is there another story of virtual hosting I am not aware of?

**Comment by hannosch** [comment]
Ah, you are right. When I moved it out, I thought it depended on some kind of publishing hook, which would no longer be there in the WSGI publisher. But it looks like it only uses the `BeforeTraverse` module, and that part of the traversal logic is still the same.

For the 2.13 WSGI publisher I also assumed people were using the full repoze stack (`repoze.tm2`, `repoze.retry`) and thus would also use `repoze.vhm`.

Given how tiny the code in SiteAccess is, I wouldn't mind putting it back into the Zope repo itself.
